.TH "ActivationFunction< T >" 3 "Mon Apr 9 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActivationFunction< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ActivationFunction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T \fBoperator()\fP (T x) const =0"
.br
.ti -1c
.RI "T \fBderiterative\fP (T x) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>class ActivationFunction< T >"
Interfejs klasy obsługującej funkcje aktywacji (przestarzałe) 
.SH "Member Function Documentation"
.PP 
.SS "template<class T > T \fBActivationFunction\fP< T >::\fBderiterative\fP (Tx) const\fC [pure virtual]\fP"Funkcja licząca pochodną funkcji skokowej (jako cos(x) w zakresie 0 do 1) 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "template<class T > T \fBActivationFunction\fP< T >::operator() (Tx) const\fC [pure virtual]\fP"Funkcja sprawdzająca czy dana wartość jest większa od podanego progu\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Sprawdzana wartość\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
true jeśli sprawdzana waratość jest większa, false w przeciwnym wypadku\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
