.TH "async_private_data" 3 "Mon Apr 9 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
async_private_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBn_channels\fP"
.br
.ti -1c
.RI "snd_pcm_sframes_t \fBperiod_size\fP"
.br
.ti -1c
.RI "signed short * \fBsamples\fP"
.br
.ti -1c
.RI "snd_pcm_channel_area_t * \fBareas\fP"
.br
.ti -1c
.RI "double \fBphase\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
