.TH "Bias< T >" 3 "Thu Apr 5 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bias< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bias\&.h>\fP
.PP
Inherits \fBInput< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBias\fP (T i)"
.br
.ti -1c
.RI "void \fBsetBias\fP (T i)"
.br
.ti -1c
.RI "void \fBsetBiasAndSend\fP (T i)"
.br
.ti -1c
.RI "void \fBsendBiasToLinks\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>class Bias< T >"
Odpowiada przesunięciu w sieciach neuronowych\&. Po podłączeniu linku należy przekazać wartość do łącz lub użyć metody \fBsetBias(T)\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBBias\fP< T >::\fBBias\fP (Ti)\fC [inline]\fP"Konstruktor ustawiający początkową wartość przesunięcia\&. Po podłączeniu linku należy przekazać wartość do łącz lub użyć metody \fBsetBias(T)\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP Wartość przesunięcia\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<class T > void \fBBias\fP< T >::\fBsendBiasToLinks\fP ()\fC [inline]\fP"Wysyła wartość przesunięcia do łącz\&. 
.SS "template<class T > void \fBBias\fP< T >::\fBsetBias\fP (Ti)\fC [inline]\fP"Ustawia wartość przesunięcia i nie wysyła jej do łącz\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP Wartość przesunięcia\&. 
.RE
.PP

.SS "template<class T > void \fBBias\fP< T >::\fBsetBiasAndSend\fP (Ti)\fC [inline]\fP"Ustawia wartość przesunięcia i wysyła ją do łącz\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP Wartość przesunięcia\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
