.TH "device_parameters" 3 "Mon Apr 9 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
device_parameters \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "snd_pcm_sframes_t \fBbuffer_size\fP"
.br
.ti -1c
.RI "snd_pcm_sframes_t \fBperiod_size\fP"
.br
.ti -1c
.RI "unsigned int \fBbuffer_time\fP"
.br
.ti -1c
.RI "unsigned int \fBperiod_time\fP"
.br
.ti -1c
.RI "int \fBn_channels\fP"
.br
.ti -1c
.RI "unsigned int \fBsample_rate\fP"
.br
.ti -1c
.RI "snd_pcm_format_t \fBsample_format\fP"
.br
.ti -1c
.RI "snd_pcm_access_t \fBaccess_type\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
