.TH "Entry< T >" 3 "Tue May 1 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Entry< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Entry\&.h>\fP
.PP
Inherits \fBInput< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetEntry\fP (T entry)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>class Entry< T >"
Klasa \fBEntry\fP odpowiada wejściom do sieci neuronowej\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<class T > void \fBEntry\fP< T >::\fBsetEntry\fP (Tentry)\fC [inline]\fP"Ustawia wejście na podaną wartość\&. 
.PP
\fBParameters:\fP
.RS 4
\fIentry\fP Żądana wartość\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
