.TH "Exit< T >" 3 "Tue May 1 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exit< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exit\&.h>\fP
.PP
Inherits \fBOutput< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T \fBgetExit\fP () const "
.br
.ti -1c
.RI "void \fBlearn\fP (T answer) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>class Exit< T >"
Klasa \fBExit\fP odpowiada wyjściom z sieci neuronowej 
.SH "Member Function Documentation"
.PP 
.SS "template<class T > T \fBExit\fP< T >::\fBgetExit\fP () const\fC [inline]\fP"Funkcja zwracająca wyjście\&. 
.PP
\fBReturns:\fP
.RS 4
Wyjście\&. 
.RE
.PP

.SS "template<class T > void \fBExit\fP< T >::\fBlearn\fP (Tanswer) const\fC [inline]\fP"Funkcja rozpoczynająca uczenienie z tego wyjścia sieci\&. 
.PP
\fBParameters:\fP
.RS 4
\fIanswer\fP Żądana odpowiedź\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
