.TH "Helper" 3 "Tue May 1 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Helper \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Helper\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBintToString\fP (int n)"
.br
.ti -1c
.RI "static std::string \fBdoubleToString\fP (double n)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Klasa udostępniająca statyczne funkcje pomocnicze\&. 
.SH "Member Function Documentation"
.PP 
.SS "string \fBHelper::doubleToString\fP (doublen)\fC [static]\fP"Funkcja zmieniająca double na std::string 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP double do zmiany\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
std::string odpowiadający danej liczbie\&. 
.RE
.PP

.SS "string \fBHelper::intToString\fP (intn)\fC [static]\fP"Funkcja zamieniająca integer na string\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP Integer, który chcemy zamienić\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
String odpowiadający tej liczbie\&. Jeśli przekazana liczba nie jest całkowita to następuje obcięcie (np\&. z 5\&.6 tworzone jest '5')\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
