.TH "io_method" 3 "Mon Apr 9 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io_method \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum_io_method \fBmethod\fP"
.br
.ti -1c
.RI "snd_pcm_access_t \fBaccess\fP"
.br
.ti -1c
.RI "int \fBopen_mode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
