.TH "Klasa" 3 "Thu Apr 5 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Klasa \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
wejściom do sieci neuronowej\&.
.PP
interfejsem wejścia do klasy \fBLink\fP\&.
.PP
połączaniu między neuronami oraz między neuronami i wejściem/wyjściem\&.
.PP
interfejsem wyjścia dla klasy \fBLink\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
