.TH "LinearActivationFunction< T >" 3 "Tue May 1 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinearActivationFunction< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LinearActivationFunction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinearActivationFunction\fP ()"
.br
.ti -1c
.RI "\fBLinearActivationFunction\fP (double p)"
.br
.ti -1c
.RI "T \fBoperator()\fP (T x)"
.br
.ti -1c
.RI "T \fBderiterative\fP (T x)"
.br
.ti -1c
.RI "void \fBsetParameter\fP (double parameter)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>class LinearActivationFunction< T >"
Klasa przedstawiającą skokową funkcję aktywacji o kształcie sigmoidy parametryzowana wartością określającą w jakim zakresie jest największa zmiana wartości\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBLinearActivationFunction\fP< T >::\fBLinearActivationFunction\fP ()\fC [inline]\fP"Konstrutor domyślny ustawiający za parametr wartość 1\&. 
.SS "template<class T > \fBLinearActivationFunction\fP< T >::\fBLinearActivationFunction\fP (doublep)\fC [inline]\fP"Konstrutor domyślny ustawiający żądany parametr\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<class T > T \fBLinearActivationFunction\fP< T >::\fBderiterative\fP (Tx)\fC [inline]\fP"Funkcja licząca pochodną 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Wartość dla której liczymy pochodną\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Obliczona pochodna\&. 
.RE
.PP

.SS "template<class T > T \fBLinearActivationFunction\fP< T >::operator() (Tx)\fC [inline]\fP"Funkcja licząca wartość sigmoidy\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Sprawdzana wartość\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Wyliczona wartość dla sigmoidy 
.RE
.PP

.SS "template<class T > void \fBLinearActivationFunction\fP< T >::\fBsetParameter\fP (doubleparameter)\fC [inline]\fP"Funkcja ustawiająca paramtr sigmoidy, 
.PP
\fBParameters:\fP
.RS 4
\fIparameter\fP Parametr\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
