.TH "NeuralNetwork< T, ActivationFunction >::WrongArgument" 3 "Thu Apr 5 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NeuralNetwork< T, ActivationFunction >::WrongArgument \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWrongArgument\fP (std::string m)"
.br
.ti -1c
.RI "std::string \fBGetMessage\fP () const "
.br
.in -1c

.SS "template<class T, class ActivationFunction> class NeuralNetwork< T, ActivationFunction >::WrongArgument"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
