.TH "NeuralNetwork< T, ActivationFunction >::WrongState" 3 "Thu Apr 5 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NeuralNetwork< T, ActivationFunction >::WrongState \- 
.SH SYNOPSIS
.br
.PP

.SS "template<class T, class ActivationFunction> class NeuralNetwork< T, ActivationFunction >::WrongState"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
