.TH "NeuralNetwork< T, ActivationFunction >::WrongState" 3 "Thu Apr 5 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NeuralNetwork< T, ActivationFunction >::WrongState \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NeuralNetwork\&.h>\fP
.SH "Detailed Description"
.PP 

.SS "template<class T, class ActivationFunction>class NeuralNetwork< T, ActivationFunction >::WrongState"
Klasa wyjątku w sytuacji, gdy próbujemy operować na sieci w sytuacji gdy jest to niemożliwe (np\&. zmienić parametry w momencie gdy sieć działa)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
