.TH "NeuralNetwork< T, ActivationFunction >::WrongArgument" 3 "Thu Apr 5 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NeuralNetwork< T, ActivationFunction >::WrongArgument \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NeuralNetwork\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWrongArgument\fP (std::string m)"
.br
.ti -1c
.RI "std::string \fBGetMessage\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T, class ActivationFunction>class NeuralNetwork< T, ActivationFunction >::WrongArgument"
Klasa wyjątku w sytuacji, gdy podany argument do funkcji jest niezgodny z aktualnie ustawionymi parametrami sieci (np\&. ustawienie ilości nuronów w 3 warstwie, jeśli sieć posiada 2 warstwy) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T , class ActivationFunction > \fBNeuralNetwork\fP< T, \fBActivationFunction\fP >::\fBWrongArgument::WrongArgument\fP (std::stringm)\fC [inline]\fP"Konstrutkor z ustawieniem wiadomości\&. 
.PP
\fBParameters:\fP
.RS 4
\fIm\fP Wiadomość do ustawienia\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<class T , class ActivationFunction > std::string \fBNeuralNetwork\fP< T, \fBActivationFunction\fP >::\fBWrongArgument::GetMessage\fP () const\fC [inline]\fP"Pobranie wiadomości przekazywanej przez wyjątek\&. 
.PP
\fBReturns:\fP
.RS 4
Wiadomość przekazana przez wyjątek\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
