.TH "Output< T >" 3 "Thu Apr 5 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Output< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Output\&.h>\fP
.PP
Inherited by \fBExit< T >\fP, and \fBNeuron< T, ActivationFunction >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetLinkIn\fP (\fBLink\fP< T > *link)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::list< \fBLink\fP< T > * > \fBins\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>class Output< T >"
Klasa \fBOutput\fP jest interfejsem wyjścia dla klasy \fBLink\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<class T> void \fBOutput\fP< T >::\fBsetLinkIn\fP (\fBLink\fP< T > *link)\fC [inline]\fP"Funkcja przyjmująca wartość z łącza\&. 
.PP
\fBParameters:\fP
.RS 4
\fIo\fP Otrzymana wartość z łącza\&. Funkcja dodająca połączenie do wyjścia z połączenia\&. 
.br
\fIlink\fP Dodawane połączenie\&. 
.RE
.PP

.PP
Reimplemented in \fBNeuron< T, ActivationFunction >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
