.TH "Output< T >" 3 "Mon Apr 9 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Output< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Output\&.h>\fP
.PP
Inherited by \fBExit< T >\fP, and \fBNeuron< T, ActivationFunction >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Output\fP ()"
.br
.ti -1c
.RI "void \fBsetLinkIn\fP (\fBLink\fP< T > *link)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::list< \fBLink\fP< T > * > \fBins\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>class Output< T >"
Klasa \fBOutput\fP jest interfejsem wyjścia dla klasy \fBLink\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T> virtual \fBOutput\fP< T >::~\fBOutput\fP ()\fC [inline, virtual]\fP"Destruktor\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<class T> void \fBOutput\fP< T >::\fBsetLinkIn\fP (\fBLink\fP< T > *link)\fC [inline]\fP"Funkcja dodająca połączenie do wyjścia z połączenia\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlink\fP Dodawane połączenie\&. 
.RE
.PP

.PP
Reimplemented in \fBNeuron< T, ActivationFunction >\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class T> std::list<\fBLink\fP<T>*> \fBOutput\fP< T >::\fBins\fP\fC [protected]\fP"Lista \fBLink\fP wejść do danego elementu\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
