.TH "StepActivationFunction< T >" 3 "Tue May 1 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StepActivationFunction< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StepActivationFunction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStepActivationFunction\fP ()"
.br
.ti -1c
.RI "\fBStepActivationFunction\fP (T i)"
.br
.ti -1c
.RI "T \fBoperator()\fP (T x)"
.br
.ti -1c
.RI "T \fBderiterative\fP (T x)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>class StepActivationFunction< T >"
Klasa przedstawiającą skokową funkcję aktywacji o określonym progu\&. Aktywacja następuje gdy dana wartość jest większa od wartości progu\&. Pochodną funkcji jest zookrąglona delta diraca\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBStepActivationFunction\fP< T >::\fBStepActivationFunction\fP ()\fC [inline]\fP"Konstrutor domyślny ustawiający za wartość 0 (rzutowaną na dany typ) 
.SS "template<class T > \fBStepActivationFunction\fP< T >::\fBStepActivationFunction\fP (Ti)\fC [inline]\fP"Konstruktor z parametrem progu\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP Próg jaki chcemy ustawić\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<class T > T \fBStepActivationFunction\fP< T >::\fBderiterative\fP (Tx)\fC [inline]\fP"Funkcja licząca pochodną funkcji skokowej (jako cos(x) w zakresie 0 do 1) 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Argument\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Wynik pochodnej\&. 
.RE
.PP

.SS "template<class T > T \fBStepActivationFunction\fP< T >::operator() (Tx)\fC [inline]\fP"Funkcja sprawdzająca czy dana wartość jest większa od podanego progu\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Sprawdzana wartość\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
1 jeśli sprawdzana waratość jest większa, 0 w przeciwnym wypadku\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
