.TH "transfer_method" 3 "Mon Apr 9 2012" "SSN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transfer_method \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "snd_pcm_access_t \fBaccess\fP"
.br
.ti -1c
.RI "int(* \fBtransfer_loop\fP )(snd_pcm_t *handle, signed short *samples, snd_pcm_channel_area_t *areas)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SSN from the source code\&.
